[build]
  command = "cd task-list-app && ng build -c production"
  publish = "task-list-app/dist/task-list-app/browser"
  functions = "netlify/functions"

[build.environment]
    PYTHON_VERSION = "3.12.4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

